### ISSUE TITLE
How to structure your code into multiple python packages?

### ISSUE THREAD

**Issue by antonioadaldo** [antonioadaldo/quadcoptersSML#3]
I seem to have trouble playing around with the architecture of the project.
I would like to give the package a structure with python packages.
There should be a py-package 'utils', and a py-package 'simulators' and a py-package 'controllers' and maybe more in the future.
But ROS seems to want that I put all my code in the same folder where the executable ROS nodes are.
For example, if my hierarchy is

    quad_control
        nodes
            simulator.py
            utils
                filters.py

then in the 'simulator.py' I can do

    import utils.filters

But if my hierarchy is

    quad_control
        nodes
            simulator.py
        utils
            filters.py

then in simulator.py I  CANNOT do

     import quad_control.utils.filters

In fact, if I try to rosrun simulator.py, I get a complaint that there is no module named utils.filters.
Ironically,

    import quad_control.msg

works just fine.

Do you know if I am doing something wrong or if there is a quick fix?
Do we maybe need to play with the PYTHONPATH variable?
Thanks in advance!

**Comment by maherzog** [comment]
Are you getting the error on the line of the import statement or when you are trying to "use" the import?

My interpretation of the [ROS python style guide (section 3)](http://wiki.ros.org/PyStyleGuide#Package.2BAC8-Module_Names_.28__init__.py_files.29) is, that you might need to change your directory structure if you want to import the packages this way. Otherwise you can only import packages in subdirectories of the directory that contains the file, so putting `utils` into `nodes` might help as well (at least I think so).

**Comment by cverginis** [comment]
That seems to work. http://wiki.ros.org/rospy_tutorials/Tutorials/Makefile

**Comment by antonioadaldo** [comment]
Thank you guys, they were both very helpful.
I did a mix of the two and now it seems to work.
In the future, we will include this sort of things in a guide or readme.
